### ISSUE TITLE
Front End - todo

### ISSUE THREAD

**Issue by source** [source/source#3]
## Home 
- [ ]  Consider alternate layout for posts (smaller thumbnail < right)
- [ ]  Styles post__content (gravatar, url, summary)
- [ ]  Mockup timeline on the side (desktop only?) **see new issue
- [ ]  Disable mobile scroll
- [ ]  Find way to separate items in desktop
- [ ]  Add button need to work **new issue
- [ ] Titlebar disappears on scroll down

## Reader
- [ ] Back button on reader mode
- [ ] Action button (reader options / view original / discussion)
- [ ] iFrame the original option

## Discussion
- [ ] Mobile Mockup - slide to the left
- [ ] Desktop Mockup - runs parallel next to article?

## Explore
- [ ] Mockup, keep it simple

## Notifications
- [ ] Mockup, keep it simple

## Profile
- [ ] Add gravatar to top?
- [ ] Background opacity on cover image
- [ ] Add profile statistics
- [ ] Paralax the main banner?
- [ ] Formatting for recent posts
